issue #478 improved README file
ioBroker/dev-server pull request #479
Opened 2024-11-06 01:50 UTC by srishtiisharmaa

2025-01-24 08:27 UTC, UncleSamSwiss requested changes

2025-01-24 08:27 UTC, UncleSamSwiss commented on README.md
> +Instead of manually editing the package.json file, users should simply run ```npm install``` to automatically install the dependencies listed in the package.json
This is common sense for NodeJS developers. I wouldn't put this in the general section of this tool.

2025-01-24 08:27 UTC, UncleSamSwiss commented on README.md
> +Users should run ```npm run dev-server``` rather than just ```dev-server```, as the latter may not work directly on Linux systems without additional setup (such as adding it to the PATH).
Combined with the remainder of the readme, this is confusing. `npm run dev-server` only works if it was added as a devDependency. If we want to keep this sentence, it should be moved to the dev-dependency section.

2025-09-09 21:38 UTC, Apollon77 commented on README.md
> +Instead of manually editing the package.json file, users should simply run ```npm install``` to automatically install the dependencies listed in the package.json
I think it is ok to state that because many devs do not know tat they need to to that e.g. to update package-lock or such ... so not the worst idea tbh

2025-09-09 21:38 UTC, Apollon77 commented on README.md
> +Instead of manually editing the package.json file, users should simply run ```npm install``` to automatically install the dependencies listed in the package.json
But the sentence in general makes no sense because npm install and changing deps are two different things.

2025-09-09 21:39 UTC, Apollon77 commented
I will close the PR because it does not make that much sense and is more conusing and maybe dev-server is not the best place for such generic ideas

2025-09-09 21:39 UTC, closed without merging